name: CI Pipeline

on:
  push:
    branches:
      - main

# Define the jobs in the workflow
jobs:
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: fdgdfdf
      run: echo "hiii"




