name: CI Pipeline

on:
  push:
    branches:
      - main

# Define the jobs in the workflow
jobs:
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: 'docker tag'
      run: docker build -t ${{ secrets.DOCKER_USER }}/newreact:1.0.0 .

    - name: 'docker push'
      run: 'docker push ${{ secrets.DOCKER_USER }}/newreact:1.0.0'


